Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -56,7 +56,12 @@ jobs:
         run: |
           chmod +x diy.sh
           ./diy.sh
-
+      - name: Check routing feed
+        working-directory: ImmortalWrt
+        run: | 
+         ls feeds | grep routing || echo "routing feed missing"
+        
+        
       - name: 更新并下载 feeds (Update and download feeds)
         working-directory: ImmortalWrt
         run: ./scripts/feeds update -a && ./scripts/feeds install -a
